#
# This site was originally deployed by Netlify to https://acim.christmind.info. This has changed
# so that it is incorporated into the Netlify site cmi-www and is accessed at
# https://www.christmind.info/t/acim.
#
# This config file is used update the cmi-acim Netlify site with a page that imforms the user
# that the site has moved and to include a _redirects file that will forward references to 
# https://acim.christmind.info to the appropriate destination.
#
# To develop this site
#
# 1. npm run deploy:netlify
# 2. Edit moved.md, _redirects and any other files
# 3. Test locally at localhost:9915
# 4. Use the command line from the project root to deploy to Netlify
#     $ netlify deploy --prod
#
# The switch from https://acim.christmind.info to https://www.christmind.info/t/acim happened
# on March 19, 2019. Maintaining the old Netlify site, cmi-acim, is needed only for a short 
# time.
#

sourceId: 15
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'A Course in Miracles'
tagline:      'Original Edition'
description:  ''
url:          'https://www.christmind.info/t/acimoe'
baseurl:      ''
keywords:     "Christ Mind Teachings, A Course in Miracles, Original Edition "
port:         9915

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

src-url:      'https://www.christmind.info/t/acimoe'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown
#plugins:
#  - jekyll-feed
#  - jekyll-sitemap

# force inclusion of
include: [_redirects]

exclude: [
  deploy,
  LICENSE,
  README.md,
  Gemfile,
  Gemfile.lock,
  package.json,
  package-lock.json,
  node_modules,
  webpack.config.js,
  src,
  project,
  _acq,
  _manual,
  _preface,
  _text,
  _workbook
]

