# CMI
destination: "../cmi-www/_site/t/acimoe"

sourceId: 15
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'ACIM Original Edition'
tagline:      'Original Edition'
description:  ''
url:          'https://www.christmind.info/t/acimoe'
baseurl:      ''
keywords:     "Christ Mind Teachings, A Course in Miracles, Original Edition "
port:         9915

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
src-url:      'https://www.christmind.info/t/acimoe'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

# Collections for transcripts
collections:
  acq:
    output: true
    title: "Get Acquainted"
  text:
    output: true
    title: "A Course in Miracles Original Edition: Text"
  workbook:
    output: true
    title: "A Course in Miracles: Workbook"
  manual:
    output: true
    title: "A Course in Miracles: Manual"

defaults:
  - scope:
      path: ""
      type: acq
    values:
      layout: transcript
      book: "Get Acquainted"
      image: "/t/acimoe/public/img/acim/acq-big.jpg"
      image-width: 612
      image-height: 792
      audio: false
      bid: "acq"
      pnumToggle: false
  - scope:
      path: ""
      type: text
    values:
      layout: transcript
      book: "Text"
      image: "/t/acimoe/public/img/acim/text.jpg"
      image-width: 612
      image-height: 792
      bid: "text"
      audio: true
  - scope:
      path: ""
      type: workbook
    values:
      layout: transcript
      book: "Workbook for Students"
      image: "/t/acimoe/public/img/acim/workbook.jpg"
      image-width: 612
      image-height: 792
      bid: "workbook"
      audio: true
  - scope:
      path: ""
      type: manual
    values:
      layout: transcript
      book: "Manual"
      image: "/t/acimoe/public/img/acim/manual.jpg"
      image-width: 612
      image-height: 792
      bid: "manual"
      audio: true

exclude: [
  moved.html, deploy, LICENSE, README.md, Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

